### ISSUE TITLE
2章AWS WAFのログ分析Athenaクエリを公開してほしい

### ISSUE THREAD

**Issue by takirer** [classmethod/aws-for-everyone#3]
第2章2.6でAWS WAFのログをAthenaで分析するハンズオンがありますが、Athenaに入力するクエリをコードとして公開してほしいです。
書籍から写経するには分量が多く辛いものがあります。

**Comment by HamadaKoji** [comment]
@takirer 

おまたせしました。chapter02にディレクトリつくって格納しております。遅くなり申し訳ございませんが、こちらご利用いただければ。

https://github.com/classmethod/aws-for-everyone/tree/master/chapter02/chapter02-06-security
